-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 14:51:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema factory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema factory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capstream` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `capstream` ;

-- -----------------------------------------------------
-- Table `capstream`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`country` (
  `idCountry` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isoCode` CHAR(2) NOT NULL,
  `active` BIT(1) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB
AUTO_INCREMENT = 247
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`province` (
  `idProvince` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCountry` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `abbr` CHAR(2) NOT NULL,
  `active` BIT(1) NOT NULL,
  PRIMARY KEY (`idProvince`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`location` (
  `idLocation` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `addressLine1` VARCHAR(255) NOT NULL,
  `addressLine2` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `idProvince` INT UNSIGNED NOT NULL,
  `idCountry` INT UNSIGNED NOT NULL,
  `postalCode` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idLocation`),
  UNIQUE INDEX `idLocation_UNIQUE` (`idLocation` ASC) VISIBLE,
  INDEX `fkLocationProvince` (`idProvince` ASC) VISIBLE,
  INDEX `fkLocationCountry` (`idCountry` ASC) VISIBLE,
  CONSTRAINT `fkLocationCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `capstream`.`country` (`idCountry`),
  CONSTRAINT `fkLocationProvince`
    FOREIGN KEY (`idProvince`)
    REFERENCES `capstream`.`province` (`idProvince`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`address` (
  `idAddress` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `recipient` VARCHAR(100) NOT NULL,
  `idLocation` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fkLocationAddress` (`idLocation` ASC) VISIBLE,
  CONSTRAINT `fkLocationAddress`
    FOREIGN KEY (`idLocation`)
    REFERENCES `capstream`.`location` (`idLocation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`alphacode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`alphacode` (
  `idAlphaCode` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(7) NOT NULL,
  `value` FLOAT NOT NULL,
  `used` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idAlphaCode`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`entity` (
  `idEntity` BINARY(16) NOT NULL,
  `entityTitle` VARCHAR(255) NULL DEFAULT NULL,
  `entityDesc` TEXT NULL DEFAULT NULL,
  `entityType` INT NOT NULL,
  `idMedia` BIGINT UNSIGNED NULL DEFAULT NULL,
  `dtCreated` DATETIME NOT NULL,
  `dtLastEdited` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idEntity`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEntity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`cart` (
  `idEntity` BINARY(16) NOT NULL,
  `idUser` BINARY(16) NOT NULL,
  `quantity` INT UNSIGNED NULL DEFAULT NULL,
  `idOffer` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEntity`, `idUser`),
  INDEX `fkUserCart` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fkEntityCart`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`),
  CONSTRAINT `fkUserCart`
    FOREIGN KEY (`idUser`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`credit-card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`credit-card` (
  `idCreditCard` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(16) NOT NULL,
  `expiration` DATE NOT NULL,
  `ccv` VARCHAR(4) NOT NULL,
  `idAddressBilling` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCreditCard`),
  INDEX `fkAddressCreditCard` (`idAddressBilling` ASC) VISIBLE,
  CONSTRAINT `fkAddressCreditCard`
    FOREIGN KEY (`idAddressBilling`)
    REFERENCES `capstream`.`address` (`idAddress`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`email` (
  `idEmail` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEntity` BINARY(16) NOT NULL,
  `emailAddress` VARCHAR(320) NOT NULL,
  `emailVerified` TINYINT(1) NULL DEFAULT NULL,
  `emailVerifyCode` CHAR(6) NOT NULL,
  PRIMARY KEY (`idEmail`),
  UNIQUE INDEX `idEmail_UNIQUE` (`idEmail` ASC) VISIBLE,
  INDEX `fkEntityEmail_idx` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityEmail`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`entity-area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`entity-area` (
  `idEntity` BINARY(16) NOT NULL,
  `idAddress` INT NULL DEFAULT NULL,
  `postalCode` VARCHAR(12) NULL DEFAULT NULL,
  `mileRadius` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`entity-media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`entity-media` (
  `idMedia` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEntity` BINARY(16) NOT NULL,
  `idUser` BINARY(16) NOT NULL,
  `mediaType` INT UNSIGNED NOT NULL,
  `fileName` VARCHAR(50) NOT NULL,
  `dtCreated` DATETIME NOT NULL,
  `sortOrder` INT NOT NULL,
  `xOffset` FLOAT NULL DEFAULT '0',
  `yOffset` FLOAT NULL DEFAULT '0',
  `scale` FLOAT NULL DEFAULT '1',
  PRIMARY KEY (`idMedia`),
  INDEX `fkEntityEM_idx` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityEM`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`entity-relate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`entity-relate` (
  `idEntity` BINARY(16) NOT NULL,
  `idRelated` BINARY(16) NOT NULL,
  `relateType` INT NOT NULL,
  PRIMARY KEY (`idEntity`, `idRelated`, `relateType`),
  INDEX `fkEntityET2` (`idRelated` ASC) VISIBLE,
  CONSTRAINT `fkEntityET`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`),
  CONSTRAINT `fkEntityET2`
    FOREIGN KEY (`idRelated`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`event` (
  `idEvent` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEntity` BINARY(16) NOT NULL,
  `eventType` TINYINT NOT NULL,
  `dtStart` DATETIME NOT NULL,
  `dtEnd` DATETIME NULL DEFAULT NULL,
  `allDay` BIT(1) NOT NULL,
  `repeatType` TINYINT NOT NULL,
  `repeatTimeFrame` TINYINT NOT NULL,
  `repeatMonthlyType` TINYINT NOT NULL,
  `repeatInterval` SMALLINT NOT NULL,
  `repeatSun` BIT(1) NOT NULL,
  `repeatMon` BIT(1) NOT NULL,
  `repeatTue` BIT(1) NOT NULL,
  `repeatWed` BIT(1) NOT NULL,
  `repeatThu` BIT(1) NOT NULL,
  `repeatFri` BIT(1) NOT NULL,
  `repeatSat` BIT(1) NOT NULL,
  `repeatEndType` TINYINT NOT NULL,
  `repeatEnd` DATETIME NULL DEFAULT NULL,
  `repeatOccurences` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`idEvent`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEvent` ASC) VISIBLE,
  INDEX `fkEntityEvent` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityEvent`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`event-chain-edit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`event-chain-edit` (
  `idEventChainEdit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEvent` INT UNSIGNED NOT NULL,
  `editType` TINYINT UNSIGNED NOT NULL,
  `dtStart` DATETIME NOT NULL,
  `idNewEvent` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEventChainEdit`),
  UNIQUE INDEX `idEventChainEdit_UNIQUE` (`idEventChainEdit` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`group` (
  `idEntity` BINARY(16) NOT NULL,
  `groupType` INT NOT NULL,
  `backgroundColor` VARCHAR(7),
  PRIMARY KEY (`idEntity`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityGroup`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`interaction` (
  `idInteraction` BIGINT NOT NULL AUTO_INCREMENT,
  `idEntity` BINARY(16) NOT NULL,
  `userPrompt` TEXT NULL DEFAULT NULL,
  `aiResponse` TEXT NULL DEFAULT NULL,
  `factoryAction` VARCHAR(255) NULL DEFAULT NULL,
  `actionParameter` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idInteraction`),
  INDEX `idEntity` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `interaction_ibfk_1`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
AUTO_INCREMENT = 249
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`item` (
  `idEntity` BINARY(16) NOT NULL,
  `condition` INT NOT NULL,
  PRIMARY KEY (`idEntity`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityItem`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`master-type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`master-type` (
  `idMasterType` INT NOT NULL AUTO_INCREMENT,
  `table` VARCHAR(100) NOT NULL,
  `column` VARCHAR(100) NOT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMasterType`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`offer` (
  `idOffer` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEntity` BINARY(16) NOT NULL,
  `offerType` SMALLINT NOT NULL,
  `confirmMethod` TINYINT NOT NULL,
  `price` FLOAT NOT NULL,
  `rateType` SMALLINT NOT NULL,
  `negotiable` TINYINT NOT NULL,
  `quantify` BIT(1) NULL DEFAULT NULL,
  `quantity` SMALLINT NOT NULL,
  PRIMARY KEY (`idOffer`),
  UNIQUE INDEX `idOffer_UNIQUE` (`idOffer` ASC) VISIBLE,
  INDEX `fkEntityOffer` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityOffer`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`person` (
  `idEntity` BINARY(16) NOT NULL,
  `personFirstName` VARCHAR(128) NULL DEFAULT NULL,
  `personLastName` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idEntity`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityPerson`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`place` (
  `idEntity` BINARY(16) NOT NULL,
  `placeType` INT NOT NULL,
  PRIMARY KEY (`idEntity`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkEntityPlace`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`user` (
  `idEntity` BINARY(16) NOT NULL,
  `userName` VARCHAR(64) NOT NULL,
  `userPassword` VARCHAR(60) NOT NULL,
  `userSalt` VARCHAR(29) NOT NULL,
  `userPrimaryEmail` BIGINT UNSIGNED NOT NULL,
  `userTimeZone` TINYINT NOT NULL,
  `accountBalance` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`idEntity`),
  UNIQUE INDEX `idEntity_UNIQUE` (`idEntity` ASC) VISIBLE,
  INDEX `fkUserEmail` (`userPrimaryEmail` ASC) VISIBLE,
  CONSTRAINT `fkEntityUser`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`),
  CONSTRAINT `fkUserEmail`
    FOREIGN KEY (`userPrimaryEmail`)
    REFERENCES `capstream`.`email` (`idEmail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`reset-password-session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`reset-password-session` (
  `idSession` BINARY(16) NOT NULL,
  `idEntity` BINARY(16) NOT NULL,
  `dtStarted` DATETIME NOT NULL,
  PRIMARY KEY (`idSession`),
  INDEX `fkUserFPS_idx` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkUserFPS`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`user` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`session` (
  `idEntity` BINARY(16) NOT NULL,
  `ipAddress` VARCHAR(255) NOT NULL,
  `browser` VARCHAR(255) NOT NULL,
  `screenWidth` INT NOT NULL,
  `screenHeight` INT NOT NULL,
  `referrerURL` VARCHAR(255) NOT NULL,
  `geolocation` VARCHAR(255) NOT NULL,
  `timeZone` VARCHAR(255) NOT NULL,
  `language` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEntity`),
  CONSTRAINT `session_ibfk_1`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`entity` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstream`.`user-session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstream`.`user-session` (
  `idSession` BINARY(16) NOT NULL,
  `idEntity` BINARY(16) NOT NULL,
  `dtStarted` DATETIME NOT NULL,
  `dtActive` DATETIME NOT NULL,
  `done` BIT(1) NOT NULL,
  PRIMARY KEY (`idSession`, `idEntity`),
  INDEX `fkUserUS` (`idEntity` ASC) VISIBLE,
  CONSTRAINT `fkUserUS`
    FOREIGN KEY (`idEntity`)
    REFERENCES `capstream`.`user` (`idEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `capstream` ;

-- -----------------------------------------------------
-- procedure deleteAddress
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteAddress`(IN p_idAddress BIGINT)
BEGIN
	DELETE FROM address WHERE idAddress = p_idAddress;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteAlphaCode
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteAlphaCode`(IN p_idAlphaCode INT)
BEGIN DELETE FROM alphacode WHERE idAlphaCode = p_idAlphaCode; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteCart
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteCart`(IN p_idUser CHAR(36))
BEGIN
	DELETE FROM cart WHERE idUser = UUID_TO_BIN(p_idUser);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteCartItem
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteCartItem`(IN p_idUser CHAR(36), IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM cart WHERE idEntity = UUID_TO_BIN(p_idEntity) AND idUser = UUID_TO_BIN(p_idUser);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteCreditCard
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteCreditCard`(IN p_idCreditCard bigint(20))
BEGIN
	DELETE FROM `credit-card` WHERE idCreditCard = p_idCreditCard;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEmail
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEmail`(IN p_idEmail BIGINT)
BEGIN
	DELETE FROM email WHERE idEmail = p_idEmail;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEntity`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM entity WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEntityArea
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEntityArea`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM `entity-area` WHERE  idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEntityMedia
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEntityMedia`(IN p_idMedia BIGINT)
BEGIN
	DELETE FROM `entity-media` WHERE idMedia = p_idMedia;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEntityMediaAll
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEntityMediaAll`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM `entity-media` WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEntityRelate
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEntityRelate`(IN p_idEntity CHAR(36), IN p_idRelated CHAR(36))
BEGIN
	DELETE FROM `entity-relate` WHERE idEntity = UUID_TO_BIN(p_idEntity) AND idRelated = UUID_TO_BIN(p_idRelated);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEntityRelateAll
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEntityRelateAll`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM `entity-relate` WHERE idEntity = UUID_TO_BIN(p_idEntity) OR idRelated = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEvent
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEvent`(IN p_idEvent BIGINT)
BEGIN
	DELETE FROM event WHERE idEvent = p_idEvent;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteEventChainEdit
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteEventChainEdit`(IN p_idEventChainEdit INT)
BEGIN
	DELETE FROM `event-chain-edit` WHERE  idEventChainEdit = p_idEventChainEdit;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteGroup
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteGroup`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM `group` WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteItem
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteItem`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM item WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteLocation
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteLocation`(IN p_idLocation BIGINT)
BEGIN
	DELETE FROM location WHERE idLocation = p_idLocation;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteMasterType
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteMasterType`(IN p_idMasterType INT)
BEGIN
	DELETE FROM `master-type` WHERE  idMasterType = p_idMasterType;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteOffer
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteOffer`(IN p_idOffer INT)
BEGIN
	DELETE FROM offer WHERE idOffer = p_idOffer;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deletePerson
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deletePerson`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM person WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deletePlace
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deletePlace`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM place WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteResetPasswordSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteResetPasswordSession`(IN p_idSession CHAR(36))
BEGIN
	DELETE FROM `reset-password-session` WHERE idSession = UUID_TO_BIN(p_idSession);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteSession`(IN p_idEntity CHAR(36))
BEGIN DELETE FROM session WHERE idEntity = UUID_TO_BIN(p_idEntity); END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteUser
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteUser`(IN p_idEntity CHAR(36))
BEGIN
	DELETE FROM user WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteUserSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteUserSession`(IN p_idSession CHAR(36))
BEGIN
	DELETE FROM `user-session` WHERE idSession = UUID_TO_BIN(p_idSession);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertAddress
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertAddress`(IN p_name varchar(100), 
    IN p_idLocation bigint(20))
BEGIN
	INSERT INTO address (name, idLocation) 
    VALUES (p_name, p_idLocation);
	SELECT LAST_INSERT_ID() AS idAddress;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertAlphaCode
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertAlphaCode`(IN p_code VARCHAR(7), IN p_value FLOAT, IN p_used BOOLEAN)
BEGIN INSERT INTO alphacode (code, value, used) VALUES (p_code, p_value, p_used); SELECT LAST_INSERT_ID() AS idAlphaCode; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertCart
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertCart`(IN p_idEntity CHAR(36), IN p_idUser CHAR(36), IN p_quantity INT, IN p_idOffer INT(10))
BEGIN
	INSERT INTO cart (idUser, idEntity, quantity, idOffer) VALUES(UUID_TO_BIN(p_idUser), UUID_TO_BIN(p_idEntity), p_quantity, p_idOffer);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertCreditCard
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertCreditCard`(IN p_number varchar(16), 
    IN p_expiration date, 
    IN p_ccv varchar(4), 
    IN p_idAddressBilling bigint(20))
BEGIN
	INSERT INTO `credit-card` (number, expiration, ccv, idAddressBilling) 
    VALUES (p_number, p_expiration, p_ccv, p_idAddressBilling);
	SELECT LAST_INSERT_ID() AS idCreditCard;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEmail
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEmail`(IN p_idEntity CHAR(36), IN p_emailAddress VARCHAR(320), IN p_emailVerifyCode CHAR(6))
BEGIN
	INSERT INTO email (idEntity, emailAddress, emailVerifyCode) VALUES(UUID_TO_BIN(p_idEntity), p_emailAddress, p_emailVerifyCode);
	SELECT LAST_INSERT_ID() AS idEmail;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEntity`(IN p_entityTitle VARCHAR(255), IN p_entityDesc TEXT, IN p_entityType INT)
BEGIN
	SET @idEntity = UUID_TO_BIN(UUID());
	INSERT INTO entity (idEntity, entityTitle, entityDesc, entityType, dtCreated) VALUES(@idEntity, p_entityTitle, p_entityDesc, p_entityType, Now());
	SELECT BIN_TO_UUID(@idEntity) as idEntity;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEntityArea
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEntityArea`(IN p_idEntity CHAR(36), IN p_idAddress INT, IN p_postalCode VARCHAR(12), IN p_mileRadius INT)
BEGIN
	INSERT INTO `entity-area` (idEntity, idAddress, postalCode, mileRadius) 
    VALUES (UUID_TO_BIN(p_idEntity), p_idAddress, p_postalCode, p_mileRadius);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEntityMedia
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEntityMedia`(IN p_idEntity CHAR(36), IN p_idUser CHAR(36), IN p_mediaType INT, IN p_fileName VARCHAR(50), IN p_sortOrder INT, IN p_xOffset FLOAT, IN p_yOffset FLOAT, IN p_scale FLOAT)
BEGIN
	INSERT INTO `entity-media` (idEntity, idUser, mediaType, fileName, dtCreated, sortOrder, xOffset, yOffset, scale) 
	VALUES(UUID_TO_BIN(p_idEntity), UUID_TO_BIN(p_idUser), p_mediaType, p_fileName, Now(), p_sortOrder, p_xOffset, p_yOffset, p_scale);
	SELECT LAST_INSERT_ID() AS idMedia;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEntityRelate
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEntityRelate`(IN p_idEntity CHAR(36), IN p_idRelated CHAR(36), IN p_relateType INT)
BEGIN
	INSERT INTO `entity-relate` (idEntity, idRelated, relateType) VALUES(UUID_TO_BIN(p_idEntity), UUID_TO_BIN(p_idRelated), p_relateType);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEvent
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEvent`(IN p_idEntity char(36),
  IN p_eventType TINYINT,
  IN p_dtStart DATETIME,
  IN p_dtEnd DATETIME,
  IN p_allDay bit(1),
  IN p_repeatType TINYINT,
  IN p_repeatTimeFrame TINYINT,
  IN p_repeatMonthlyType TINYINT,
  IN p_repeatInterval SMALLINT,
  IN p_repeatSun bit(1),
  IN p_repeatMon bit(1),
  IN p_repeatTue bit(1),
  IN p_repeatWed bit(1),
  IN p_repeatThu bit(1),
  IN p_repeatFri bit(1),
  IN p_repeatSat bit(1),
  IN p_repeatEndType tinyint,
  IN p_repeatEnd datetime,
  IN p_repeatOccurences smallint, 
  IN p_allServices bit(1))
BEGIN
	INSERT INTO event (idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices) 
    VALUES (UUID_TO_BIN(p_idEntity),
            p_eventType,
            p_dtStart,
            p_dtEnd,
            p_allDay,
            p_repeatType,
            p_repeatTimeFrame,
            p_repeatMonthlyType,
            p_repeatInterval,
            p_repeatSun,
            p_repeatMon,
            p_repeatTue,
            p_repeatWed,
            p_repeatThu,
            p_repeatFri,
            p_repeatSat,
            p_repeatEndType,
            p_repeatEnd,
            p_repeatOccurences, 
            p_allServices);
	SELECT LAST_INSERT_ID() AS idEvent;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertEventChainEdit
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertEventChainEdit`(IN p_idEvent int(10), IN p_editType tinyint, IN p_dtStart datetime, IN p_idNewEvent CHAR(36))
BEGIN
	INSERT INTO `event-chain-edit` (idEvent, editType, dtStart, idNewEvent) VALUES(p_idEvent, p_editType, p_dtStart, p_idNewEvent);
	SELECT LAST_INSERT_ID() as idEventChainEdit;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertGroup
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertGroup`(IN p_idEntity CHAR(36), IN p_groupType INT)
BEGIN
	INSERT INTO `group` (idEntity, groupType) VALUES(UUID_TO_BIN(p_idEntity), groupType);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertInteraction
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertInteraction`(IN p_idEntity CHAR(36), IN p_userPrompt TEXT, IN p_aiResponse TEXT, IN p_factoryAction VARCHAR(255), IN p_actionParameter VARCHAR(255))
BEGIN INSERT INTO interaction (idEntity, userPrompt, aiResponse, factoryAction, actionParameter) VALUES (UUID_TO_BIN(p_idEntity), p_userPrompt, p_aiResponse, p_factoryAction, p_actionParameter); SELECT LAST_INSERT_ID() AS idInteraction; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertItem
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertItem`(IN p_idEntity CHAR(36), IN p_condition INT)
BEGIN
	INSERT INTO item (idEntity, `condition`) VALUES(UUID_TO_BIN(p_idEntity), p_condition);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertLocation
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertLocation`(IN p_addressLine1 varchar(255), 
    IN p_addressLine2 varchar(255), 
    IN p_city varchar(255), 
    IN p_idProvince int(10), 
    IN p_idCountry int(10),
    IN p_postalCode varchar(12))
BEGIN
	INSERT INTO location (addressLine1, addressLine2, city, idProvince, idCountry, postalCode) 
    VALUES (p_addressLine1, p_addressLine2, p_city, p_idProvince, p_idCountry, p_postalCode);
	SELECT LAST_INSERT_ID() AS idLocation;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertMasterType
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMasterType`(IN p_table VARCHAR(100), IN p_column VARCHAR(100), IN p_value VARCHAR(255), IN p_code VARCHAR(45))
BEGIN
	INSERT INTO `master-type` (`table`, `column`, value, code) VALUES (p_table, p_column, p_value, p_code);
	SELECT LAST_INSERTED_ID() as idMasterType;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertOffer
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertOffer`(IN p_idEntity CHAR(36), 
    IN p_offerType smallint, 
    IN p_confirmMethod TINYINT,
    IN p_price float, 
    IN p_rateType smallint, 
    IN p_negotiable bit(1),
    IN p_quantify bit(1),
    IN p_quantity smallint,
    IN p_minTimeIncrement smallint,
    IN p_maxTimeIncrement SMALLINT,
    IN p_startTimeIncrement SMALLINT,
    IN p_bookingLeadNumber SMALLINT,
    IN p_bookingLeadType SMALLINT,
    IN p_cancelLeadNumber SMALLINT,
    IN p_cancelLeadType SMALLINT,
    IN p_cancelFee FLOAT,
    IN p_handlePayment bit(1),
    IN p_depositRequired TINYINT,
    IN p_cancelPolicyOn bit(1),
    IN p_cancelFeeType TINYINT,
    IN p_depositAmountType TINYINT,
    IN p_depositAmount FLOAT,
    IN p_serviceLocation TINYINT)
BEGIN
	INSERT INTO offer (idEntity, offerType, confirmMethod, price, rateType, negotiable, quantify, quantity, minTimeIncrement, maxTimeIncrement, startTimeIncrement, bookingLeadNumber, bookingLeadType, cancelLeadNumber, cancelLeadType, cancelFee, handlePayment, depositRequired, cancelPolicyOn, cancelFeeType, depositAmountType, depositAmount, serviceLocation) 
    VALUES (UUID_TO_BIN(p_idEntity), p_offerType, p_confirmMethod, p_price, p_rateType, p_negotiable, p_quantify, p_quantity, p_minTimeIncrement, p_maxTimeIncrement, p_startTimeIncrement, p_bookingLeadNumber, p_bookingLeadType, p_cancelLeadNumber, p_cancelLeadType, p_cancelFee, p_handlePayment, p_depositRequired, p_cancelPolicyOn, p_cancelFeeType, p_depositAmountType, p_depositAmount, p_serviceLocation);
  SELECT LAST_INSERT_ID() AS idOffer;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertPerson
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertPerson`(IN p_idEntity CHAR(36), IN p_personFirstName VARCHAR(128), IN p_personLastName VARCHAR(128))
BEGIN
	INSERT INTO person (idEntity, personFirstName, personLastName) VALUES(UUID_TO_BIN(p_idEntity), p_personFirstName, p_personLastName);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertPlace
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertPlace`(IN p_idEntity CHAR(36), IN p_placeType INT)
BEGIN
	INSERT INTO place (idEntity, placeType) VALUES(UUID_TO_BIN(p_idEntity), placeType);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertResetPasswordSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertResetPasswordSession`(IN p_idEntity CHAR(36))
BEGIN
	SET @idSession = UUID();
	INSERT INTO `reset-password-session` (idSession, idEntity, dtStarted) VALUES(UUID_TO_BIN(@idSession), UUID_TO_BIN(p_idEntity), Now());
	SELECT @idSession as idSession;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertSession`(IN p_idEntity CHAR(36), IN p_ipAddress VARCHAR(255), IN p_browser VARCHAR(255), IN p_screenWidth INT, IN p_screenHeight INT, IN p_referrerURL VARCHAR(255), IN p_geolocation VARCHAR(255), IN p_timeZone VARCHAR(255), IN p_language VARCHAR(255))
BEGIN INSERT INTO session (idEntity, ipAddress, browser, screenWidth, screenHeight, referrerURL, geolocation, timeZone, language) VALUES (UUID_TO_BIN(p_idEntity), p_ipAddress, p_browser, p_screenWidth, p_screenHeight, p_referrerURL, p_geolocation, p_timeZone, p_language); SELECT p_idEntity AS idEntity; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertUser
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertUser`(IN p_idEntity CHAR(36), IN p_userName VARCHAR(255), IN p_userPassword VARCHAR(255), IN p_userSalt VARCHAR(255), IN p_userPrimaryEmail BIGINT, IN p_userTimeZone TINYINT, IN p_accountBalance FLOAT)
BEGIN
    INSERT INTO user (idEntity, userName, userPassword, userSalt, userPrimaryEmail, userTimeZone, accountBalance) VALUES(UUID_TO_BIN(p_idEntity), p_userName, p_userPassword, p_userSalt, p_userPrimaryEmail, p_userTimeZone, p_accountBalance);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertUserSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertUserSession`(IN p_idEntity CHAR(36))
BEGIN
	SET @idSession = UUID();
	SET @Now = Now();
	INSERT INTO `user-session` (idSession, idEntity, dtStarted, dtActive, done) VALUES(UUID_TO_BIN(@idSession), UUID_TO_BIN(p_idEntity), @Now, @Now, 0);
	SELECT @idSession as idSession;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectAddress
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectAddress`(IN p_idAddress bigint(20))
BEGIN
	SELECT idAddress, name, idLocation 
    FROM address
    WHERE idAddress = p_idAddress;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectAlphaCodeByCode
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectAlphaCodeByCode`(IN p_code VARCHAR(7))
BEGIN SELECT idAlphaCode, code, value, used FROM alphacode WHERE code = p_code; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectCart
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectCart`(IN p_idUser CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) AS idEntity, BIN_TO_UUID(idUser) AS idUser, quantity, idOffer
    	FROM cart as c
    	WHERE c.idUser = UUID_TO_BIN(p_idUser);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectCountryActive
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectCountryActive`()
BEGIN
	SELECT * FROM country WHERE active = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectCreditCard
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectCreditCard`(IN p_idCreditCard bigint(20))
BEGIN
	SELECT idCreditCard, number, expiration, ccv, idAddressBilling
    FROM `credit-card`
    WHERE idCreditCard = p_idCreditCard;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEmail
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEmail`(IN p_idEmail BIGINT)
BEGIN
	SELECT idEmail, BIN_TO_UUID(idEntity) as idEntity, emailAddress, emailVerified, emailVerifyCode FROM email WHERE idEmail = p_idEmail;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEmailByEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEmailByEntity`(IN p_idEntity CHAR(36))
BEGIN
	SELECT idEmail, BIN_TO_UUID(idEntity) as idEntity, emailAddress, emailVerified, emailVerifyCode FROM email WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntity`(IN p_idEntity CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) AS idEntity, entityTitle, entityDesc, entityType, idMedia, dtCreated, dtLastEdited  FROM entity WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityArea
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityArea`(IN p_idEntity CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) as idEntity, idAddress, postalCode, mileRadius FROM `entity-area` where idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityByEntityType
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityByEntityType`(IN p_entityType INT)
BEGIN
	SELECT BIN_TO_UUID(idEntity) AS idEntity, entityTitle, entityDesc, entityType, idMedia, dtCreated, dtLastEdited FROM entity WHERE entityType = p_entityType;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityByOwner
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityByOwner`(IN p_idEntity CHAR(36), IN p_entityType INT)
BEGIN
	SELECT BIN_TO_UUID(e.idEntity) AS idEntity, e.entityTitle, e.entityDesc, e.entityType, e.idMedia, e.dtCreated, e.dtLastEdited, 
    o.idOffer, o.offerType, o.confirmMethod, o.price, o.rateType, o.negotiable, o.quantify, o.quantity, 
	o.minTimeIncrement, o.maxTimeIncrement, o.startTimeIncrement, o.bookingLeadNumber, o.bookingLeadType,
	o.cancelLeadNumber, o.cancelLeadType, o.cancelFee, o.handlePayment, o.depositRequired, o.cancelPolicyOn, o.cancelFeeType, o.depositAmountType, o.depositAmount
	FROM entity AS e 
		RIGHT JOIN `entity-relate` AS er ON er.idEntity = e.idEntity
		LEFT OUTER JOIN offer AS o ON o.idEntity = e.idEntity
	WHERE idRelated = UUID_TO_BIN(p_idEntity) AND er.relateType = 1 AND entityType = p_entityType
	ORDER BY dtCreated DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityBySearch
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityBySearch`(IN p_searchValue CHAR(255))
BEGIN
  SELECT * FROM 
	  (SELECT BIN_TO_UUID(e.idEntity) AS idEntity, e.entityTitle, e.entityDesc, e.entityType, e.idMedia, e.dtCreated, e.dtLastEdited, em.fileName, em.mediaType, em.xOffset, em.yOffset 
		FROM entity AS e, `entity-media` as em
		WHERE e.idMedia = em.idMedia
	  UNION ALL 
	  SELECT BIN_TO_UUID(e.idEntity) AS idEntity, e.entityTitle, e.entityDesc, e.entityType, e.idMedia, e.dtCreated, e.dtLastEdited, NULL, NULL, 0, 0
		FROM entity AS e
		WHERE e.idMedia is NULL) `combined-alias`
	 ORDER BY dtCreated DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityMedia
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityMedia`(IN p_idMedia BIGINT)
BEGIN
	SELECT idMedia, BIN_TO_UUID(idEntity) as idEntity, BIN_TO_UUID(idUser) as idUser, mediaType, fileName, dtCreated, sortOrder, xOffset, yOffset, scale 
	FROM `entity-media` WHERE idMedia = p_idMedia;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityMediaByEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityMediaByEntity`(IN p_idEntity CHAR(36))
BEGIN
	SELECT idMedia, BIN_TO_UUID(idEntity) as idEntity, BIN_TO_UUID(idUser) as idUser, mediaType, fileName, dtCreated, sortOrder, xOffset, yOffset, scale
	FROM `entity-media` WHERE idEntity = UUID_TO_BIN(p_idEntity) ORDER BY sortOrder ASC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityRelate
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityRelate`(IN p_idEntity CHAR(36), IN p_relateType INT)
BEGIN
	(SELECT BIN_TO_UUID(e.idEntity) AS idEntity, e.entityTitle, e.entityDesc, e.entityType, e.idMedia, e.dtCreated, e.dtLastEdited, em.fileName, em.mediaType, em.xOffset, em.yOffset, em.scale 
		FROM entity AS e, `entity-media` as em, `entity-relate` as er
		WHERE er.idEntity = UUID_TO_BIN(p_idEntity) AND er.relateType = p_relateType AND er.idRelated = e.idEntity AND e.idMedia = em.idMedia)
	UNION ALL 
  	(SELECT BIN_TO_UUID(e.idEntity) AS idEntity, e.entityTitle, e.entityDesc, e.entityType, e.idMedia, e.dtCreated, e.dtLastEdited, NULL as fileName, NULL as mediaType, 0 as xOffset, 0 as yOffset, 0 as scale
    	FROM entity AS e, `entity-relate` as er
    	WHERE er.idEntity = UUID_TO_BIN(p_idEntity) AND er.relateType = p_relateType AND er.idRelated = e.idEntity AND e.idMedia is NULL);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEntityRelateByRelated
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEntityRelateByRelated`(IN p_idRelated CHAR(36))
BEGIN
	SELECT * FROM `entity-relate` WHERE idRelated = UUID_TO_BIN(p_idRelated);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEvent
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEvent`(IN p_idEntity CHAR(36))
BEGIN
	SELECT idEvent, 
            BIN_TO_UUID(idEntity) as idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices
    FROM event
    WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectEventChainEdit
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectEventChainEdit`(IN p_idEvent INT)
BEGIN
	SELECT idEventChainEdit, idEvent, editType, dtStart, idNewEvent FROM `event-chain-edit` where idEvent = p_idEvent;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectGroup
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectGroup`(IN p_idEntity CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) as idEntity, groupType FROM `group` where idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectItem
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectItem`(IN p_idEntity CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) as idEntity, `condition` FROM item WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectLocation
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectLocation`(IN p_idLocation bigint(20))
BEGIN
	SELECT idLocation, addressLine1, addressLine2, city, idProvince, idCountry, postalCode 
    FROM location
    WHERE idLocation = p_idLocation;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectMasterType
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectMasterType`(IN p_idMasterType INT)
BEGIN
	SELECT * FROM `master-type` WHERE idMasterType = p_idMasterType;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectMasterTypeByValue
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectMasterTypeByValue`(IN p_value VARCHAR(255))
BEGIN
	SELECT * FROM `master-type` WHERE value = p_value;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectOffer
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectOffer`(IN p_idOffer bigint(20))
BEGIN
	SELECT idOffer, BIN_TO_UUID(idEntity) AS idEntity, offerType, confirmMethod, price, rateType, negotiable, quantify, quantity, minTimeIncrement, maxTimeIncrement, startTimeIncrement, bookingLeadNumber, bookingLeadType, cancelLeadNumber, cancelLeadType, cancelFee, handlePayment, depositRequired, cancelPolicyOn, cancelFeeType, depositAmountType, depositAmount, serviceLocation
  FROM offer
  WHERE idOffer = p_idOffer;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectOfferForEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectOfferForEntity`(IN p_idEntity CHAR(36))
BEGIN
	SELECT idOffer, BIN_TO_UUID(idEntity) AS idEntity,offerType, confirmMethod, price, rateType, negotiable, quantify, quantity, minTimeIncrement, maxTimeIncrement, startTimeIncrement, bookingLeadNumber, bookingLeadType, cancelLeadNumber, cancelLeadType, cancelFee, handlePayment, depositRequired, cancelPolicyOn, cancelFeeType, depositAmountType, depositAmount, serviceLocation
  FROM offer
  WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectPerson
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectPerson`(IN p_idEntity CHAR(36))
BEGIN
	SELECT * FROM person WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectPlace
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectPlace`(IN p_idEntity CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) as idEntity, placeType FROM place where idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectProviderUnconfirmedCount
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectProviderUnconfirmedCount`(IN p_idEntity CHAR(36))
BEGIN
    SELECT COUNT(e.idEvent) as unconfirmedBookings
    FROM event AS e, booking AS b
    WHERE e.idEntity = UUID_TO_BIN(p_idEntity) AND eventType = 3 AND e.idEvent = b.idEvent AND confirmed = 0;    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectProvinceByCountry
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectProvinceByCountry`(IN p_idCountry INT)
BEGIN
	SELECT * FROM province WHERE idCountry = p_idCountry AND active = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectResetPasswordSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectResetPasswordSession`(IN p_idSession CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idSession) AS idSession, BIN_TO_UUID(idEntity) AS idEntity, dtStarted 
	FROM `reset-password-session` WHERE idSession = UUID_TO_BIN(p_idSession);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectSession`(IN p_idEntity CHAR(36))
BEGIN SELECT BIN_TO_UUID(idEntity) as idEntity, ipAddress, browser, screenWidth, screenHeight, referrerURL, geolocation, timeZone, language FROM session WHERE idEntity = UUID_TO_BIN(p_idEntity); END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectUser
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectUser`(IN p_idEntity CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) as idEntity, userName, userPassword, userSalt, userPrimaryEmail, userTimeZone FROM user WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectUserByEmail
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectUserByEmail`(IN p_emailAddress VARCHAR(320))
BEGIN
	SELECT BIN_TO_UUID(u.idEntity) as idEntity, u.userName, u.userPassword, u.userSalt, u.userPrimaryEmail, e.emailAddress, e.emailVerified, u.userTimeZone, u.accountBalance, p.personFirstName, p.personLastName
	FROM user AS u, email AS e, person p 
    WHERE u.idEntity = e.idEntity AND p.idEntity = u.idEntity AND e.emailAddress = p_emailAddress;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectUserByUserName
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectUserByUserName`(IN p_userName CHAR(64))
BEGIN
	SELECT BIN_TO_UUID(u.idEntity) as idEntity, u.userName, u.userPassword, u.userSalt, u.userPrimaryEmail, e.entityTitle, u.userTimeZone
    FROM user AS u, entity AS e
    WHERE userName = p_userName AND e.idEntity = u.idEntity;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectUserEvents
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectUserEvents`(IN p_idEntity CHAR(36))
BEGIN
	(SELECT idEvent, 
            BIN_TO_UUID(idEntity) as idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices,
            null as idBooking,
            null as idAvailability,
            null as idConsumer,
            null as consumerTitle,
            null as idService,
            null as confirmed
    FROM event
    WHERE idEntity = UUID_TO_BIN(p_idEntity) AND eventType < 2)
    UNION ALL 
    (SELECT e.idEvent, 
            BIN_TO_UUID(e.idEntity) as idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices,
            idBooking,
            idAvailability,
            BIN_TO_UUID(idConsumer) as idConsumer,
            en.entityTitle as consumerTitle,
            BIN_TO_UUID(idService) as idService,
            confirmed
    FROM event AS e, booking AS b, entity AS en
    WHERE e.idEntity = UUID_TO_BIN(p_idEntity) AND eventType = 3 AND e.idEvent = b.idEvent AND en.idEntity = b.idConsumer AND confirmed <> 2)
    ORDER BY eventType ASC, dtStart ASC, dtEnd ASC, idService ASC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectUserSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectUserSession`(IN p_idSession CHAR(36))
BEGIN
	SELECT BIN_TO_UUID( idSession) as idSession, BIN_TO_UUID( idEntity ) as idEntity, dtStarted, dtActive, done
	FROM `user-session` WHERE idSession = UUID_TO_BIN(p_idSession);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateAddress
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateAddress`(IN p_idAddress bigint(20), 
    IN p_name varchar(100), 
    IN p_idLocation  bigint(20))
BEGIN
	UPDATE address 
    SET name = p_name, idLocation = p_idLocation 
    WHERE idAddress = p_idAddress;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateAlphaCode
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateAlphaCode`(IN p_idAlphaCode INT, IN p_code VARCHAR(7), IN p_value FLOAT, IN p_used BOOLEAN)
BEGIN UPDATE alphacode SET code = p_code, value = p_value, used = p_used WHERE idAlphaCode = p_idAlphaCode; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateCartItem
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateCartItem`(IN p_idEntity CHAR(36), IN p_idUser CHAR(36), IN p_quantity INT, IN p_idOffer INT(10))
BEGIN
	UPDATE cart SET quantity=p_quantity, idOffer=p_idOffer WHERE idUser = UUID_TO_BIN(p_idUser) AND idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateCreditCard
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateCreditCard`(IN p_idCreditCard bigint(20), 
    IN p_number varchar(16), 
    IN p_expiration date, 
    IN p_ccv varchar(4), 
    IN p_idAddressBilling bigint(20))
BEGIN
	UPDATE `credit-card` 
    SET number = p_number, expiration = p_expiration, ccv = p_ccv, idAddressBilling = p_idAddressBilling
    WHERE idCreditCard = p_idCreditCard;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateEmail
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateEmail`(IN p_idEmail BIGINT, IN p_emailAddress VARCHAR(320), IN p_emailVerified TINYINT(1), IN p_emailVerifyCode CHAR(6))
BEGIN
	UPDATE email SET emailAddress = p_emailAddress, emailVerified = p_emailVerified, emailVerifyCode = p_emailVerifyCode WHERE idEmail = p_idEmail;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateEntity
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateEntity`(IN p_idEntity CHAR(36), IN p_entityTitle VARCHAR(255), IN p_entityDesc TEXT)
BEGIN
	UPDATE entity 
  SET entityTitle = p_entityTitle, entityDesc = p_entityDesc, dtLastEdited = Now() 
  WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateEntityArea
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateEntityArea`(IN p_idEntity CHAR(36), IN p_idAddress INT, IN p_postalCode VARCHAR(12), IN p_mileRadius INT)
BEGIN
	UPDATE `entity-area` SET idAddress = p_idAddress, postalCode = p_postalCode, mileRadius = p_mileRadius
	WHERE  idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateEntityMedia
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateEntityMedia`(IN p_idMedia BIGINT, IN p_sortOrder INT, IN p_xOffset FLOAT, IN p_yOffset FLOAT, IN p_scale FLOAT)
BEGIN
	UPDATE `entity-media` SET sortOrder = p_sortOrder, xOffset = p_xOffset, yOffset = p_yOffset, scale = p_scale WHERE idMedia = p_idMedia;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateEntityPrimaryMedia
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateEntityPrimaryMedia`(IN p_idEntity CHAR(36), IN p_idMedia BIGINT)
BEGIN
  UPDATE entity
  SET idMedia = p_idMedia
  WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateEvent
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateEvent`(IN p_idEvent bigint, 
  IN p_idEntity char(36),
  IN p_eventType TINYINT,
  IN p_dtStart DATETIME,
  IN p_dtEnd DATETIME,
  IN p_allDay bit(1),
  IN p_repeatType TINYINT,
  IN p_repeatTimeFrame TINYINT,
  IN p_repeatMonthlyType TINYINT,
  IN p_repeatInterval SMALLINT,
  IN p_repeatSun bit(1),
  IN p_repeatMon bit(1),
  IN p_repeatTue bit(1),
  IN p_repeatWed bit(1),
  IN p_repeatThu bit(1),
  IN p_repeatFri bit(1),
  IN p_repeatSat bit(1),
  IN p_repeatEndType tinyint,
  IN p_repeatEnd datetime,
  IN p_repeatOccurences smallint,
  IN p_allServices bit(1))
BEGIN
	UPDATE event 
    SET idEntity = UUID_TO_BIN(p_idEntity),
          eventType = p_eventType,
          dtStart = p_dtStart,
          dtEnd = p_dtEnd,
          allDay = p_allDay,
          repeatType = p_repeatType,
          repeatTimeFrame = p_repeatTimeFrame,
          repeatMonthlyType = p_repeatMonthlyType,
          repeatInterval = p_repeatInterval,
          repeatSun = p_repeatSun,
          repeatMon = p_repeatMon,
          repeatTue = p_repeatTue,
          repeatWed = p_repeatWed,
          repeatThu = p_repeatThu,
          repeatFri = p_repeatFri,
          repeatSat = p_repeatSat,
          repeatEndType = p_repeatEndType,
          repeatEnd = p_repeatEnd,
          repeatOccurences = p_repeatOccurences,
          allServices = p_allServices
    WHERE idEvent = p_idEvent;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateGroup
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateGroup`(IN p_idEntity CHAR(36), IN p_groupType INT)
BEGIN
	UPDATE `group` SET groupType = p_groupType WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateItem
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateItem`(IN p_idEntity CHAR(36), IN p_condition INT)
BEGIN
	UPDATE item SET `condition`=p_condition WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateLocation
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateLocation`(IN p_idLocation bigint(20), 
    IN p_addressLine1 varchar(255), 
    IN p_addressLine2 varchar(255), 
    IN p_city varchar(255), 
    IN p_idProvince int(10), 
    IN p_idCountry int(10),
    IN p_postalCode varchar(12))
BEGIN
	UPDATE location 
    SET addressLine1 = p_addressLine1, addressLine2 = p_addressLine2, city = p_city, 
        idProvince = p_idProvince, idCountry = p_idCountry, postalCode = p_postalCode 
    WHERE idLocation = p_idLocation;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateMasterType
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMasterType`(IN p_idMasterType INT, IN p_attrDesc VARCHAR(1024), IN p_attrType INT, IN p_idSuggestor CHAR(36))
BEGIN
	UPDATE `master-type` SET `table` = p_table, `column` = p_column, value = p_value, code = p_code
	WHERE  idMasterType = p_idMasterType;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateOffer
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateOffer`(IN p_idOffer bigint(20), 
    IN p_idEntity CHAR(36),
    IN p_offerType smallint, 
    IN p_confirmMethod TINYINT,
    IN p_price float, 
    IN p_rateType smallint,
    IN p_negotiable bit(1),
    IN p_quantify bit(1),
    IN p_quantity smallint,
    IN p_minTimeIncrement smallint,
    IN p_maxTimeIncrement SMALLINT,
    IN p_startTimeIncrement SMALLINT,
    IN p_bookingLeadNumber SMALLINT,
    IN p_bookingLeadType SMALLINT,
    IN p_cancelLeadNumber SMALLINT,
    IN p_cancelLeadType SMALLINT,
    IN p_cancelFee FLOAT,
    IN p_handlePayment bit(1),
    IN p_depositRequired TINYINT,
    IN p_cancelPolicyOn bit(1),
    IN p_cancelFeeType TINYINT,
    IN p_depositAmountType TINYINT,
    IN p_depositAmount FLOAT,
    IN p_serviceLocation TINYINT)
BEGIN
	UPDATE offer 
  SET offerType=p_offerType, confirmMethod=p_confirmMethod, price=p_price, rateType=p_rateType, negotiable=p_negotiable, quantify=p_quantify, quantity=p_quantity,  
    minTimeIncrement=p_minTimeIncrement, maxTimeIncrement = p_maxTimeIncrement, startTimeIncrement = p_startTimeIncrement, 
    bookingLeadNumber = p_bookingLeadNumber, bookingLeadType = p_bookingLeadType, 
    cancelLeadNumber = p_cancelLeadNumber, cancelLeadType = p_cancelLeadType, 
    cancelFee = p_cancelFee, handlePayment = p_handlePayment, depositRequired = p_depositRequired, cancelPolicyOn=p_cancelPolicyOn, cancelFeeType = p_cancelFeeType,
    depositAmountType = p_depositAmountType, depositAmount = p_depositAmount, serviceLocation = p_serviceLocation
  WHERE idOffer = p_idOffer AND idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updatePerson
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updatePerson`(IN p_idEntity CHAR(36), IN p_personFirstName VARCHAR(128), IN p_personLastName VARCHAR(128))
BEGIN
	UPDATE person SET personFirstName = p_personFirstName, personLastName = p_personLastName WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updatePlace
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updatePlace`(IN p_idEntity CHAR(36), IN p_placeType INT)
BEGIN
	UPDATE place SET placeType = p_placeType WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateSession`(IN p_idEntity CHAR(36), IN p_ipAddress VARCHAR(255), IN p_browser VARCHAR(255), IN p_screenWidth INT, IN p_screenHeight INT, IN p_referrerURL VARCHAR(255), IN p_geolocation VARCHAR(255), IN p_timeZone VARCHAR(255), IN p_language VARCHAR(255))
BEGIN UPDATE session SET ipAddress = p_ipAddress, browser = p_browser, screenWidth = p_screenWidth, screenHeight = p_screenHeight, referrerURL = p_referrerURL, geolocation = p_geolocation, timeZone = p_timeZone, language = p_language WHERE idEntity = UUID_TO_BIN(p_idEntity); END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateUser
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUser`(IN p_idEntity CHAR(36), IN p_userName VARCHAR(255), IN p_userPassword VARCHAR(255), IN p_userSalt VARCHAR(255), IN p_userPrimaryEmail BIGINT, IN p_userTimeZone TINYINT, IN p_accountBalance FLOAT)
BEGIN
    UPDATE user SET userName = p_userName, userPassword = p_userPassword, userSalt = p_userSalt, userPrimaryEmail = p_userPrimaryEmail, userTimeZone = p_userTimeZone, accountBalance = p_accountBalance WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateUserBalance
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUserBalance`(IN p_idEntity CHAR(36), IN p_accountBalance FLOAT)
BEGIN
    UPDATE user SET accountBalance = p_accountBalance WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateUserName
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUserName`(IN p_idEntity CHAR(36), IN p_userName VARCHAR(64))
BEGIN
	UPDATE user SET userName = p_userName WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateUserPrimaryEmail
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUserPrimaryEmail`(IN p_idEntity CHAR(36), IN p_userPrimaryEmail BIGINT)
BEGIN
	UPDATE user SET userPrimaryEmail = p_userPrimaryEmail WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateUserProfile
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUserProfile`(IN p_idEntity CHAR(36), IN p_userName VARCHAR(64), IN p_userTimeZone TINYINT)
BEGIN
	UPDATE user SET userName = p_userName, userTimeZone = p_userTimeZone WHERE idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateUserSession
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUserSession`(IN p_idSession CHAR(36), IN p_idEntity CHAR(36), IN p_done BIT(1))
BEGIN
	UPDATE `user-session` SET dtActive = Now(), done = p_done WHERE idSession = UUID_TO_BIN(p_idSession) AND idEntity = UUID_TO_BIN(p_idEntity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure verifyEntityRelate
-- -----------------------------------------------------

DELIMITER $$
USE `capstream`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `verifyEntityRelate`(IN p_idEntity CHAR(36), IN p_idRelated CHAR(36))
BEGIN
	SELECT BIN_TO_UUID(idEntity) as idEntity, relateType, BIN_TO_UUID(idRelated) as idRelated 
	FROM `entity-relate` 
	WHERE idEntity = UUID_TO_BIN(p_idEntity) AND idRelated = UUID_TO_BIN(p_idRelated);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
