// edit sections:
export const SECTION_NONE = 0
export const SECTION_TITLE = 1
export const SECTION_MEDIA = 2
export const SECTION_RATE = 3
export const SECTION_SERVICE_LOCATION = 4
export const SECTION_DESCRIPTION = 5
export const SECTION_CATEGORIES = 6
export const SECTION_CANCELLATION_POLICY = 7
export const SECTION_DEPOSIT_REQUIREMENTS = 8
export const SECTION_BOOKING_SETTINGS = 9
export const SECTION_TIME_BLOCK_OPTIONS = 10

const entityEditSection = {
    SECTION_NONE,
    SECTION_TITLE,
    SECTION_MEDIA,
    SECTION_RATE,
    SECTION_SERVICE_LOCATION,
    SECTION_DESCRIPTION,
    SECTION_CATEGORIES,
    SECTION_CANCELLATION_POLICY,
    SECTION_DEPOSIT_REQUIREMENTS,
    SECTION_BOOKING_SETTINGS,
    SECTION_TIME_BLOCK_OPTIONS
}

export default entityEditSection