DELIMITER //
DROP TABLE IF EXISTS hub.event//
CREATE TABLE `hub`.`event` (
  `idEvent` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEntity`  BINARY(16) NOT NULL,
  `eventType` TINYINT NOT NULL,
  `dtStart` DATETIME NOT NULL,
  `dtEnd` DATETIME DEFAULT NULL,
  `allDay` bit(1) NOT NULL,
  `repeatType` TINYINT NOT NULL,
  `repeatTimeFrame` TINYINT NOT NULL,
  `repeatMonthlyType` TINYINT NOT NULL,
  `repeatInterval` SMALLINT NOT NULL,
  `repeatSun` bit(1) NOT NULL,
  `repeatMon` bit(1) NOT NULL,
  `repeatTue` bit(1) NOT NULL,
  `repeatWed` bit(1) NOT NULL,
  `repeatThu` bit(1) NOT NULL,
  `repeatFri` bit(1) NOT NULL,
  `repeatSat` bit(1) NOT NULL,
  `repeatEndType` tinyint NOT NULL,
  `repeatEnd` datetime NULL,
  `repeatOccurences` smallint null,
  `allServices`  bit(1) NOT NULL,
  PRIMARY KEY (`idEvent`),
  UNIQUE KEY `idEntity_UNIQUE` (`idEvent`),
  CONSTRAINT `fkEntityEvent` FOREIGN KEY (`idEntity`) REFERENCES `entity` (`identity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci//

DROP PROCEDURE IF EXISTS hub.insertEvent//
CREATE PROCEDURE hub.insertEvent (IN p_idEntity char(36),
  IN p_eventType TINYINT,
  IN p_dtStart DATETIME,
  IN p_dtEnd DATETIME,
  IN p_allDay bit(1),
  IN p_repeatType TINYINT,
  IN p_repeatTimeFrame TINYINT,
  IN p_repeatMonthlyType TINYINT,
  IN p_repeatInterval SMALLINT,
  IN p_repeatSun bit(1),
  IN p_repeatMon bit(1),
  IN p_repeatTue bit(1),
  IN p_repeatWed bit(1),
  IN p_repeatThu bit(1),
  IN p_repeatFri bit(1),
  IN p_repeatSat bit(1),
  IN p_repeatEndType tinyint,
  IN p_repeatEnd datetime,
  IN p_repeatOccurences smallint, 
  IN p_allServices bit(1))
BEGIN
	INSERT INTO hub.event (idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices) 
    VALUES (UUID_TO_BIN(p_idEntity),
            p_eventType,
            p_dtStart,
            p_dtEnd,
            p_allDay,
            p_repeatType,
            p_repeatTimeFrame,
            p_repeatMonthlyType,
            p_repeatInterval,
            p_repeatSun,
            p_repeatMon,
            p_repeatTue,
            p_repeatWed,
            p_repeatThu,
            p_repeatFri,
            p_repeatSat,
            p_repeatEndType,
            p_repeatEnd,
            p_repeatOccurences, 
            p_allServices);
	SELECT LAST_INSERT_ID() AS idEvent;
END//
DROP PROCEDURE IF EXISTS hub.selectEvent//
CREATE PROCEDURE hub.selectEvent (IN p_idEntity CHAR(36))
BEGIN
	SELECT idEvent, 
            BIN_TO_UUID(idEntity) as idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices
    FROM hub.event
    WHERE idEntity = UUID_TO_BIN(p_idEntity);
END//
DROP PROCEDURE IF EXISTS hub.selectUserEvents//
CREATE PROCEDURE hub.selectUserEvents (IN p_idEntity CHAR(36))
BEGIN
	(SELECT idEvent, 
            BIN_TO_UUID(idEntity) as idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices,
            null as idAvailability,
            null as idConsumer,
            null as idService
    FROM hub.event
    WHERE idEntity = UUID_TO_BIN(p_idEntity) AND eventType < 2)
    UNION ALL 
    (SELECT e.idEvent, 
            BIN_TO_UUID(idEntity) as idEntity,
            eventType,
            dtStart,
            dtEnd,
            allDay,
            repeatType,
            repeatTimeFrame,
            repeatMonthlyType,
            repeatInterval,
            repeatSun,
            repeatMon,
            repeatTue,
            repeatWed,
            repeatThu,
            repeatFri,
            repeatSat,
            repeatEndType,
            repeatEnd,
            repeatOccurences,
            allServices,
            idAvailability,
            BIN_TO_UUID(idConsumer) as idConsumer,
            BIN_TO_UUID(idService) as idService
    FROM hub.event AS e, hub.booking AS b
    WHERE idEntity = UUID_TO_BIN(p_idEntity) AND eventType = 3 AND e.idEvent = b.idEvent);
END//
DROP PROCEDURE IF EXISTS hub.updateEvent//
CREATE PROCEDURE hub.updateEvent  (IN p_idEvent bigint, 
  IN p_idEntity char(36),
  IN p_eventType TINYINT,
  IN p_dtStart DATETIME,
  IN p_dtEnd DATETIME,
  IN p_allDay bit(1),
  IN p_repeatType TINYINT,
  IN p_repeatTimeFrame TINYINT,
  IN p_repeatMonthlyType TINYINT,
  IN p_repeatInterval SMALLINT,
  IN p_repeatSun bit(1),
  IN p_repeatMon bit(1),
  IN p_repeatTue bit(1),
  IN p_repeatWed bit(1),
  IN p_repeatThu bit(1),
  IN p_repeatFri bit(1),
  IN p_repeatSat bit(1),
  IN p_repeatEndType tinyint,
  IN p_repeatEnd datetime,
  IN p_repeatOccurences smallint,
  IN p_allServices bit(1))
BEGIN
	UPDATE hub.event 
    SET idEntity = UUID_TO_BIN(p_idEntity),
          eventType = p_eventType,
          dtStart = p_dtStart,
          dtEnd = p_dtEnd,
          allDay = p_allDay,
          repeatType = p_repeatType,
          repeatTimeFrame = p_repeatTimeFrame,
          repeatMonthlyType = p_repeatMonthlyType,
          repeatInterval = p_repeatInterval,
          repeatSun = p_repeatSun,
          repeatMon = p_repeatMon,
          repeatTue = p_repeatTue,
          repeatWed = p_repeatWed,
          repeatThu = p_repeatThu,
          repeatFri = p_repeatFri,
          repeatSat = p_repeatSat,
          repeatEndType = p_repeatEndType,
          repeatEnd = p_repeatEnd,
          repeatOccurences = p_repeatOccurences,
          allServices = p_allServices
    WHERE idEvent = p_idEvent;
END//
DROP PROCEDURE IF EXISTS hub.deleteEvent//
CREATE PROCEDURE hub.deleteEvent (IN p_idEvent BIGINT)
BEGIN
	DELETE FROM hub.event WHERE idEvent = p_idEvent;
END//