# run location.sql after this!
DROP TABLE  IF EXISTS hub.location;
DROP TABLE IF EXISTS hub.country;
CREATE TABLE `hub`.`country` (
  `idCountry` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(45) NOT NULL,
  `code` CHAR(2) NOT NULL,
  `active` BIT NOT NULL,
  PRIMARY KEY (`idCountry`));

DROP TABLE IF EXISTS hub.province;
CREATE TABLE `hub`.`province` (
  `idProvince` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `idCountry` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` CHAR(2) NOT NULL,
  `active` BIT NOT NULL,
  PRIMARY KEY (`idProvince`));
INSERT INTO hub.country (name, code, active) values ("Åland Islands","AX",0);
INSERT INTO hub.country (name, code, active) values ("Afghanistan","AF",0);
INSERT INTO hub.country (name, code, active) values ("Albania","AL",0);
INSERT INTO hub.country (name, code, active) values ("Algeria","DZ",0);
INSERT INTO hub.country (name, code, active) values ("American Samoa","AS",0);
INSERT INTO hub.country (name, code, active) values ("Andorra","AD",0);
INSERT INTO hub.country (name, code, active) values ("Angola","AO",0);
INSERT INTO hub.country (name, code, active) values ("Anguilla","AI",0);
INSERT INTO hub.country (name, code, active) values ("Antarctica","AQ",0);
INSERT INTO hub.country (name, code, active) values ("Antigua & Barbuda","AG",0);
INSERT INTO hub.country (name, code, active) values ("Argentina","AR",0);
INSERT INTO hub.country (name, code, active) values ("Armenia","AM",0);
INSERT INTO hub.country (name, code, active) values ("Aruba","AW",0);
INSERT INTO hub.country (name, code, active) values ("Australia","AU",0);
INSERT INTO hub.country (name, code, active) values ("Austria","AT",0);
INSERT INTO hub.country (name, code, active) values ("Azerbaijan","AZ",0);
INSERT INTO hub.country (name, code, active) values ("Bahamas","BS",0);
INSERT INTO hub.country (name, code, active) values ("Bahrain","BH",0);
INSERT INTO hub.country (name, code, active) values ("Bangladesh","BD",0);
INSERT INTO hub.country (name, code, active) values ("Barbados","BB",0);
INSERT INTO hub.country (name, code, active) values ("Belarus","BY",0);
INSERT INTO hub.country (name, code, active) values ("Belgium","BE",0);
INSERT INTO hub.country (name, code, active) values ("Belize","BZ",0);
INSERT INTO hub.country (name, code, active) values ("Benin","BJ",0);
INSERT INTO hub.country (name, code, active) values ("Bermuda","BM",0);
INSERT INTO hub.country (name, code, active) values ("Bhutan","BT",0);
INSERT INTO hub.country (name, code, active) values ("Bolivia","BO",0);
INSERT INTO hub.country (name, code, active) values ("Bonaire, Sint Eustatius and Saba","BQ",0);
INSERT INTO hub.country (name, code, active) values ("Bosnia & Herzegovina","BA",0);
INSERT INTO hub.country (name, code, active) values ("Botswana","BW",0);
INSERT INTO hub.country (name, code, active) values ("Bouvet Island","BV",0);
INSERT INTO hub.country (name, code, active) values ("Brazil","BR",0);
INSERT INTO hub.country (name, code, active) values ("British Indian Ocean Territory","IO",0);
INSERT INTO hub.country (name, code, active) values ("Brunei-Darussalam","BN",0);
INSERT INTO hub.country (name, code, active) values ("Bulgaria","BG",0);
INSERT INTO hub.country (name, code, active) values ("Burkina Faso","BF",0);
INSERT INTO hub.country (name, code, active) values ("Burundi","BI",0);
INSERT INTO hub.country (name, code, active) values ("Côte D'Ivoire (Ivory Coast)","CI",0);
INSERT INTO hub.country (name, code, active) values ("Cambodia","KH",0);
INSERT INTO hub.country (name, code, active) values ("Cameroon","CM",0);
INSERT INTO hub.country (name, code, active) values ("Canada","CA",1);
INSERT INTO hub.country (name, code, active) values ("Cape Verde","CV",0);
INSERT INTO hub.country (name, code, active) values ("Cayman Islands","KY",0);
INSERT INTO hub.country (name, code, active) values ("Central African Republic","CF",0);
INSERT INTO hub.country (name, code, active) values ("Chad","TD",0);
INSERT INTO hub.country (name, code, active) values ("Chile","CL",0);
INSERT INTO hub.country (name, code, active) values ("China","CN",0);
INSERT INTO hub.country (name, code, active) values ("Chrismas Island","CX",0);
INSERT INTO hub.country (name, code, active) values ("Cocos (Keeling) Islands","CC",0);
INSERT INTO hub.country (name, code, active) values ("Collectivity of Saint Martin","MF",0);
INSERT INTO hub.country (name, code, active) values ("Colombia","CO",0);
INSERT INTO hub.country (name, code, active) values ("Comoros","KM",0);
INSERT INTO hub.country (name, code, active) values ("Congo","CG",0);
INSERT INTO hub.country (name, code, active) values ("Congo, Democratic Republic","CD",0);
INSERT INTO hub.country (name, code, active) values ("Cook Islands","CK",0);
INSERT INTO hub.country (name, code, active) values ("Costa Rica","CR",0);
INSERT INTO hub.country (name, code, active) values ("Croatia","HR",0);
INSERT INTO hub.country (name, code, active) values ("Cuba","CU",0);
INSERT INTO hub.country (name, code, active) values ("Curaçao","CW",0);
INSERT INTO hub.country (name, code, active) values ("Cyprus","CY",0);
INSERT INTO hub.country (name, code, active) values ("Czech Republic","CZ",0);
INSERT INTO hub.country (name, code, active) values ("Denmark","DK",0);
INSERT INTO hub.country (name, code, active) values ("Djibouti","DJ",0);
INSERT INTO hub.country (name, code, active) values ("Dominica","DM",0);
INSERT INTO hub.country (name, code, active) values ("Dominican Republic","DO",0);
INSERT INTO hub.country (name, code, active) values ("Ecuador","EC",0);
INSERT INTO hub.country (name, code, active) values ("Egypt","EG",0);
INSERT INTO hub.country (name, code, active) values ("El Salvador","SV",0);
INSERT INTO hub.country (name, code, active) values ("Equatorial Guinea","GQ",0);
INSERT INTO hub.country (name, code, active) values ("Eritrea","ER",0);
INSERT INTO hub.country (name, code, active) values ("Estonia","EE",0);
INSERT INTO hub.country (name, code, active) values ("Ethiopia","ET",0);
INSERT INTO hub.country (name, code, active) values ("Falkand Islands (Malvinas)","FK",0);
INSERT INTO hub.country (name, code, active) values ("Faroe Islands","FO",0);
INSERT INTO hub.country (name, code, active) values ("Fiji","FJ",0);
INSERT INTO hub.country (name, code, active) values ("Finland","FI",0);
INSERT INTO hub.country (name, code, active) values ("France","FR",0);
INSERT INTO hub.country (name, code, active) values ("French Guiana","GF",0);
INSERT INTO hub.country (name, code, active) values ("French Polynesia","PF",0);
INSERT INTO hub.country (name, code, active) values ("French Southern Territories","TF",0);
INSERT INTO hub.country (name, code, active) values ("Gabon","GA",0);
INSERT INTO hub.country (name, code, active) values ("Gambia","GM",0);
INSERT INTO hub.country (name, code, active) values ("Georgia","GE",0);
INSERT INTO hub.country (name, code, active) values ("Germany","DE",0);
INSERT INTO hub.country (name, code, active) values ("Ghana","GH",0);
INSERT INTO hub.country (name, code, active) values ("Gibraltar","GI",0);
INSERT INTO hub.country (name, code, active) values ("Greece","GR",0);
INSERT INTO hub.country (name, code, active) values ("Greenland","GL",0);
INSERT INTO hub.country (name, code, active) values ("Grenada","GD",0);
INSERT INTO hub.country (name, code, active) values ("Guadeloupe","GP",0);
INSERT INTO hub.country (name, code, active) values ("Guam","GU",0);
INSERT INTO hub.country (name, code, active) values ("Guatemala","GT",0);
INSERT INTO hub.country (name, code, active) values ("Guinea","GN",0);
INSERT INTO hub.country (name, code, active) values ("Guinea-Bissau","GW",0);
INSERT INTO hub.country (name, code, active) values ("Guyana","GY",0);
INSERT INTO hub.country (name, code, active) values ("Haiti","HT",0);
INSERT INTO hub.country (name, code, active) values ("Heard Island And McDonald Islands","HM",0);
INSERT INTO hub.country (name, code, active) values ("Honduras","HN",0);
INSERT INTO hub.country (name, code, active) values ("Hong Kong","HK",0);
INSERT INTO hub.country (name, code, active) values ("Hungary","HU",0);
INSERT INTO hub.country (name, code, active) values ("Iceland","IS",0);
INSERT INTO hub.country (name, code, active) values ("India","IN",0);
INSERT INTO hub.country (name, code, active) values ("Indonesia","ID",0);
INSERT INTO hub.country (name, code, active) values ("Iran","IR",0);
INSERT INTO hub.country (name, code, active) values ("Iraq","IQ",0);
INSERT INTO hub.country (name, code, active) values ("Ireland","IE",0);
INSERT INTO hub.country (name, code, active) values ("Israel","IL",0);
INSERT INTO hub.country (name, code, active) values ("Italy","IT",0);
INSERT INTO hub.country (name, code, active) values ("Jamaica","JM",0);
INSERT INTO hub.country (name, code, active) values ("Japan","JP",0);
INSERT INTO hub.country (name, code, active) values ("Jordan","JO",0);
INSERT INTO hub.country (name, code, active) values ("Kazakhstan","KZ",0);
INSERT INTO hub.country (name, code, active) values ("Kenya","KE",0);
INSERT INTO hub.country (name, code, active) values ("Kiribati","KI",0);
INSERT INTO hub.country (name, code, active) values ("Kuwait","KW",0);
INSERT INTO hub.country (name, code, active) values ("Kyrgyzstan","KG",0);
INSERT INTO hub.country (name, code, active) values ("Laos","LA",0);
INSERT INTO hub.country (name, code, active) values ("Latvia","LV",0);
INSERT INTO hub.country (name, code, active) values ("Lebanon","LB",0);
INSERT INTO hub.country (name, code, active) values ("Lesotho","LS",0);
INSERT INTO hub.country (name, code, active) values ("Liberia","LR",0);
INSERT INTO hub.country (name, code, active) values ("Libyan Arab Jamahiriya","LY",0);
INSERT INTO hub.country (name, code, active) values ("Liechtenstein","LI",0);
INSERT INTO hub.country (name, code, active) values ("Lithuania","LT",0);
INSERT INTO hub.country (name, code, active) values ("Luxembourg","LU",0);
INSERT INTO hub.country (name, code, active) values ("Macao","MO",0);
INSERT INTO hub.country (name, code, active) values ("Macedonia  (former YR)","MK",0);
INSERT INTO hub.country (name, code, active) values ("Madagascar","MG",0);
INSERT INTO hub.country (name, code, active) values ("Malawi","MW",0);
INSERT INTO hub.country (name, code, active) values ("Malaysia","MY",0);
INSERT INTO hub.country (name, code, active) values ("Maldives (Maladive Ilands)","MV",0);
INSERT INTO hub.country (name, code, active) values ("Mali","ML",0);
INSERT INTO hub.country (name, code, active) values ("Malta","MT",0);
INSERT INTO hub.country (name, code, active) values ("Marshall Islands","MH",0);
INSERT INTO hub.country (name, code, active) values ("Martinique","MQ",0);
INSERT INTO hub.country (name, code, active) values ("Mauritania","MR",0);
INSERT INTO hub.country (name, code, active) values ("Mauritius","MU",0);
INSERT INTO hub.country (name, code, active) values ("Mayotte","YT",0);
INSERT INTO hub.country (name, code, active) values ("Mexico","MX",0);
INSERT INTO hub.country (name, code, active) values ("Micronesia  (Federa States of)","FM",0);
INSERT INTO hub.country (name, code, active) values ("Moldova, Republic of","MD",0);
INSERT INTO hub.country (name, code, active) values ("Monaco","MC",0);
INSERT INTO hub.country (name, code, active) values ("Mongolia","MN",0);
INSERT INTO hub.country (name, code, active) values ("Montenegro","ME",0);
INSERT INTO hub.country (name, code, active) values ("Montserrat","MS",0);
INSERT INTO hub.country (name, code, active) values ("Morocco","MA",0);
INSERT INTO hub.country (name, code, active) values ("Mozambique","MZ",0);
INSERT INTO hub.country (name, code, active) values ("Myanmar (Burma)","MM",0);
INSERT INTO hub.country (name, code, active) values ("Namibia","NA",0);
INSERT INTO hub.country (name, code, active) values ("Nauru","NR",0);
INSERT INTO hub.country (name, code, active) values ("Nepal","NP",0);
INSERT INTO hub.country (name, code, active) values ("Netherlands","NL",0);
INSERT INTO hub.country (name, code, active) values ("Netherlands Antilles","AN",0);
INSERT INTO hub.country (name, code, active) values ("New Caledonia","NC",0);
INSERT INTO hub.country (name, code, active) values ("New Zealand","NZ",0);
INSERT INTO hub.country (name, code, active) values ("Nicaragua","NI",0);
INSERT INTO hub.country (name, code, active) values ("Niger","NE",0);
INSERT INTO hub.country (name, code, active) values ("Nigeria","NG",0);
INSERT INTO hub.country (name, code, active) values ("Niue","NU",0);
INSERT INTO hub.country (name, code, active) values ("Norfolk Island","NF",0);
INSERT INTO hub.country (name, code, active) values ("North Korea","KP",0);
INSERT INTO hub.country (name, code, active) values ("Northern Mariana Islands","MP",0);
INSERT INTO hub.country (name, code, active) values ("Norway","NO",0);
INSERT INTO hub.country (name, code, active) values ("Oman","OM",0);
INSERT INTO hub.country (name, code, active) values ("Pakistan","PK",0);
INSERT INTO hub.country (name, code, active) values ("Palau","PW",0);
INSERT INTO hub.country (name, code, active) values ("Palestinian Territory, Occupied","PS",0);
INSERT INTO hub.country (name, code, active) values ("Panama","PA",0);
INSERT INTO hub.country (name, code, active) values ("Papua-New Guinea","PG",0);
INSERT INTO hub.country (name, code, active) values ("Paraguay","PY",0);
INSERT INTO hub.country (name, code, active) values ("Peru","PE",0);
INSERT INTO hub.country (name, code, active) values ("Philippines","PH",0);
INSERT INTO hub.country (name, code, active) values ("Pitcairn","PN",0);
INSERT INTO hub.country (name, code, active) values ("Poland","PL",0);
INSERT INTO hub.country (name, code, active) values ("Portugal","PT",0);
INSERT INTO hub.country (name, code, active) values ("Puerto Rico","PR",0);
INSERT INTO hub.country (name, code, active) values ("Quatar","QA",0);
INSERT INTO hub.country (name, code, active) values ("Reunion","RE",0);
INSERT INTO hub.country (name, code, active) values ("Romania","RO",0);
INSERT INTO hub.country (name, code, active) values ("Russian Federation","RU",0);
INSERT INTO hub.country (name, code, active) values ("Rwanda","RW",0);
INSERT INTO hub.country (name, code, active) values ("Saint Barthélemy","BL",0);
INSERT INTO hub.country (name, code, active) values ("Saint Helena, Ascension and Tristan da Cunha","SH",0);
INSERT INTO hub.country (name, code, active) values ("Saint Pierre And Micquelon","PM",0);
INSERT INTO hub.country (name, code, active) values ("San Marino","SM",0);
INSERT INTO hub.country (name, code, active) values ("Sao Tome & Principe","ST",0);
INSERT INTO hub.country (name, code, active) values ("Saudi Arabia","SA",0);
INSERT INTO hub.country (name, code, active) values ("Senegal","SN",0);
INSERT INTO hub.country (name, code, active) values ("Serbia","RS",0);
INSERT INTO hub.country (name, code, active) values ("Seychelles","SC",0);
INSERT INTO hub.country (name, code, active) values ("Sierra Leone","SL",0);
INSERT INTO hub.country (name, code, active) values ("Singapore","SG",0);
INSERT INTO hub.country (name, code, active) values ("Sint-Maarten","SX",0);
INSERT INTO hub.country (name, code, active) values ("Slovakia","SK",0);
INSERT INTO hub.country (name, code, active) values ("Slovenia","SI",0);
INSERT INTO hub.country (name, code, active) values ("Solomon Islands","SB",0);
INSERT INTO hub.country (name, code, active) values ("Somalia","SO",0);
INSERT INTO hub.country (name, code, active) values ("South Africa","ZA",0);
INSERT INTO hub.country (name, code, active) values ("South Georgia & South Sandwich Islands","GS",0);
INSERT INTO hub.country (name, code, active) values ("South Korea","KR",0);
INSERT INTO hub.country (name, code, active) values ("Spain","ES",0);
INSERT INTO hub.country (name, code, active) values ("Sri Lanka","LK",0);
INSERT INTO hub.country (name, code, active) values ("St. Kitts & Nevis","KN",0);
INSERT INTO hub.country (name, code, active) values ("St. Lucia","LC",0);
INSERT INTO hub.country (name, code, active) values ("St. Vincent & Grenadines","VC",0);
INSERT INTO hub.country (name, code, active) values ("Sudan","SD",0);
INSERT INTO hub.country (name, code, active) values ("Suriname","SR",0);
INSERT INTO hub.country (name, code, active) values ("Svalbard And Jan Mayen","SJ",0);
INSERT INTO hub.country (name, code, active) values ("Swaziland","SZ",0);
INSERT INTO hub.country (name, code, active) values ("Sweden","SE",0);
INSERT INTO hub.country (name, code, active) values ("Switzerland","CH",0);
INSERT INTO hub.country (name, code, active) values ("Syrian Arab Republic","SY",0);
INSERT INTO hub.country (name, code, active) values ("Taiwan","TW",0);
INSERT INTO hub.country (name, code, active) values ("Tajikistan","TJ",0);
INSERT INTO hub.country (name, code, active) values ("Tanzania","TZ",0);
INSERT INTO hub.country (name, code, active) values ("Thailand","TH",0);
INSERT INTO hub.country (name, code, active) values ("Timor-Leste","TL",0);
INSERT INTO hub.country (name, code, active) values ("Togo","TG",0);
INSERT INTO hub.country (name, code, active) values ("Tokelau","TK",0);
INSERT INTO hub.country (name, code, active) values ("Tonga","TO",0);
INSERT INTO hub.country (name, code, active) values ("Trinidad & Tobago","TT",0);
INSERT INTO hub.country (name, code, active) values ("Tunisia","TN",0);
INSERT INTO hub.country (name, code, active) values ("Turkey","TR",0);
INSERT INTO hub.country (name, code, active) values ("Turkmenistan","TM",0);
INSERT INTO hub.country (name, code, active) values ("Turks And Caicos Islands","TC",0);
INSERT INTO hub.country (name, code, active) values ("Tuvalu","TV",0);
INSERT INTO hub.country (name, code, active) values ("Uganda","UG",0);
INSERT INTO hub.country (name, code, active) values ("Ukraine","UA",0);
INSERT INTO hub.country (name, code, active) values ("United Arab Emirates","AE",0);
INSERT INTO hub.country (name, code, active) values ("United Kingdom","GB",0);
INSERT INTO hub.country (name, code, active) values ("United States","US",1);
INSERT INTO hub.country (name, code, active) values ("United States Minor Outlying Islands","UM",0);
INSERT INTO hub.country (name, code, active) values ("Uruguay","UY",0);
INSERT INTO hub.country (name, code, active) values ("Uzbekistan","UZ",0);
INSERT INTO hub.country (name, code, active) values ("Vanuatu","VU",0);
INSERT INTO hub.country (name, code, active) values ("Vatican City","VA",0);
INSERT INTO hub.country (name, code, active) values ("Venezuela","VE",0);
INSERT INTO hub.country (name, code, active) values ("Vietnam","VN",0);
INSERT INTO hub.country (name, code, active) values ("Virgin Islands, British","VG",0);
INSERT INTO hub.country (name, code, active) values ("Virgin Islands, U.S.","VI",0);
INSERT INTO hub.country (name, code, active) values ("Wallis And Futuna","WF",0);
INSERT INTO hub.country (name, code, active) values ("Western Sahara","EH",0);
INSERT INTO hub.country (name, code, active) values ("Western Samoa","WS",0);
INSERT INTO hub.country (name, code, active) values ("Yemen","YE",0);
INSERT INTO hub.country (name, code, active) values ("Zambia","ZM",0);
INSERT INTO hub.country (name, code, active) values ("Zimbabwe","ZW",0);

INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Alabama','AL',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Alaska','AK',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'American Samoa','AS',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Arizona','AZ',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Arkansas','AR',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'California','CA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Colorado','CO',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Connecticut','CT',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Delaware','DE',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'District of Columbia','DC',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Federated States of Micronesia','FM',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Florida','FL',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Georgia','GA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Guam','GU',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Hawaii','HI',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Idaho','ID',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Illinois','IL',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Indiana','IN',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Iowa','IA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Kansas','KS',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Kentucky','KY',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Louisiana','LA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Maine','ME',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Marshall Islands','MH',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Maryland','MD',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Massachusetts','MA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Michigan','MI',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Minnesota','MN',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Mississippi','MS',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Missouri','MO',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Montana','MT',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Nebraska','NE',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Nevada','NV',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'New Hampshire','NH',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'New Jersey','NJ',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'New Mexico','NM',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'New York','NY',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'North Carolina','NC',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'North Dakota','ND',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Northern Mariana Islands','MP',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Ohio','OH',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Oklahoma','OK',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Oregon','OR',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Palau','PW',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Pennsylvania','PA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Puerto Rico','PR',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Rhode Island','RI',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'South Carolina','SC',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'South Dakota','SD',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Tennessee','TN',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Texas','TX',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Utah','UT',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Vermont','VT',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Virgin Islands','VI',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Virginia','VA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Washington','WA',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'West Virginia','WV',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Wisconsin','WI',1);
INSERT INTO hub.province (idCountry, name, code, active) values (231, 'Wyoming','WY',1);

INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Alberta','AB',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'British Columbia','BC',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Manitoba','MB',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'New Brunswick','NB',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Newfoundland and Labrador','NL',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Northwest Territories','NT',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Nova Scotia','NS',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Nunavut','NU',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Ontario','ON',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Prince Edward Island','PE',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Quebec','QC',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Saskatchewan','SK',1);
INSERT INTO hub.province (idCountry, name, code, active) values (41, 'Yukon','YT',1);

DELIMITER //
DROP PROCEDURE IF EXISTS hub.selectCountryActive//
CREATE PROCEDURE hub.selectCountryActive ()
BEGIN
	SELECT * FROM hub.country WHERE active = 1;
END//
DROP PROCEDURE IF EXISTS hub.selectProvinceByCountry//
CREATE PROCEDURE hub.selectProvinceByCountry (IN p_idCountry INT)
BEGIN
	SELECT * FROM hub.province WHERE idCountry = p_idCountry AND active = 1;
END//
